### ISSUE TITLE
Implement better deadzones for joypads

### ISSUE THREAD

**Issue by Dudemanjude** [TwistedTwigleg/Godot_FPS_Tutorial#13]
Your implementation of the joypad deadzone doesn't work quite right. Read [this](http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html). It shows how, and why that type of deadzone is wrong. Hope this helps, and nice tutorial!

**Comment by TwistedTwigleg** [comment]
Thanks Dudemanjude!

After reading the article, I agree that my deadzone implementation could use some tweaking. Thanks for sharing the article!

**Comment by TwistedTwigleg** [comment]
Thanks Dudemanjude!

Now the joypad can make precise movements, something I didn't realize made such a big difference until I implemented the scaled radial dead zone code.
