### ISSUE TITLE
Performance drops in Test_Level.tscn

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/Godot_FPS_Tutorial#2]
(Moved from #1 )

### Poor performance on fairly powerful devices

40 fps but very strong freezes

___

Likely due to the number of static collision shapes in the level, or perhaps the volume of nodes in general. Performance is fine in `Testing_Area.tscn`.

Performance does not increase when the `GI_Probe` is deleted, when the player is deleted, when the `WorldEnviroment` is deleted, nor when some of the sections (like `Room_red` and `Room_blue`) are hidden. Changing the physics FPS to a higher value does not do anything, and changing it to a lower value causes more freezes.

Any suggestions/help would be greatly appreciated!

**Comment by Akira1San** [comment]
In windows 8.1 using the latest Godot build works smooth. How about using a smaller panorama image? I did changed it to 2048x1024. However i have not yet downloaded any sound files. Maybe its from the sound?
Edit: Its possible the frame drop to be from the mouse - MOUSE_MODE_CAPTURED. When i changed it to MOUSE_MODE_CONFINED, it got smooth.

**Comment by TwistedTwigleg** [comment]
Yeah, I will need to make a PR to replace the panorama image. I didn't realize it was so large when I first uploaded :sweat_smile: I'll replace it sometime tomorrow, as it's rather late where I am right now.

That's interesting about the mouse, I didn't even think to check that. I'll have to look into it!

Thanks for the suggestions!

Edit: WOW... I quickly looked at the panorama image, and I did not realize it was an 8K image :scream: That definitely has to change, as that is way overkill for the tutorial (and for games in general). I'll for sure fix it tomorrow.

**Comment by TwistedTwigleg** [comment]
I just changed the panorama image to a more reasonable size (`2048x1024`). Thanks for the suggestion Akira1San! I lowed the `Radiance Size` as well. Performance is much better now. It still freezes occasionally, but at least its less noticeable.

I tried changing the mouse settings but I didn't notice any improvements in performance. I'll have to do further testing later, but at least on Linux it seems the mouse is not the cause of the freezes (though it may be contributing)

I did notice the freezes went away when the project was exported. I'm wondering now if the freezes are due to the editor and not the project.

Can someone else test the project exported and see if there is any freezes? If there is no freezes with the exports, I think we can close this issue as it is likely the occasionally freeze is due to the game running in the editor.

**Comment by Akira1San** [comment]
I tested it, but its hard to tell since its unplayable in Windows because of the mouse captured issue. And it looks like it an old bug since the 2x series. Link: https://godotdevelopers.org/forum/discussion/comment/19232/#Comment_19232 But this controller ( https://github.com/Maujoe/godot-camera-control ) work in the 3 options, except when i turn on MOUSE_MODE_CAPTURED, also it locks the keyboard too.
Ive made 2 vids:
https://youtu.be/3B7Vr-WOo4s
https://youtu.be/Ijxtghvk1ec

**Comment by TwistedTwigleg** [comment]
Thanks for the videos! I think I know what to do now to fix the mouse issue. I'll do some tests, and will hopefully have a workaround soon.

Now I totally see what you are saying about the mouse impacting performance! Hopefully we can find a fix for it.

**Comment by Akira1San** [comment]
Thank you. :)

**Comment by TwistedTwigleg** [comment]
I think everything should be better now. I've tested with my Windows 10 machine and everything seems to be smooth. Now the mouse doesn't seem to be lagging things up, and `Test_Level.tscn` also seems to not have those freezes anymore.

Does someone mind testing `working_branch` with Godot 3.0.2 just to make sure this issue is fixed?

**Comment by Akira1San** [comment]
Tested it, but the mouse does the same thing. Maybe a little better, but it still jumps while moving.
And looks like somebody made an issue about the mouse mode.
link: https://github.com/godotengine/godot/issues/17288

**Comment by TwistedTwigleg** [comment]
So I guess it is a Godot bug then? I didn't notice any mouse jumping when I was testing, but maybe its due to my version of Windows? Or maybe my mouse?

Regardless, I guess the mouse problem is a Godot engine issue, and not a issue we can fix here. Was performance any better in `Test_Level.tscn`? If performance in `Test_Level.tscn` is better, than we should close this issue.

@Soarex16, do you mind testing as well? Hopefully performance is better using Godot 3.0.2 and `working_branch` than it was in #1

**Comment by Soarex16** [comment]
Indeed, when exporting, the performance is high (tested with "export in debug mode" turned on and off). I wonder why the editor sees such a decline in performance (although it feels like this is not a low performance, and the editor for some operations (possibly for statistics) performs a kind of "interruption" of the project)

**Comment by TwistedTwigleg** [comment]
Great! Then I think it is safe to close this issue, as it seems to be something relating to the Godot editor.
I will close it once I merge ``working_branch`` into master.

Thanks for the help guys! 👍 

I did a quick search and it seems there is not any open issue relating to the editor causing performance issues, so maybe we should open a issue on the Godot repository? What do you guys think?

**Comment by Soarex16** [comment]
I tested it on master :D

**Comment by Akira1San** [comment]
Yes its a Godot mouse bug.

**Comment by TwistedTwigleg** [comment]
> Soarex16 said:
> I tested it on master :D

Oh, in that case I guess I can close it now. 😄 

> Akira1San said:
> Yes its a Godot mouse bug.

The one you posted right? Or do we need to make a new issue? (I’m hesitant to open a new issue because I do not have any mouse issues on my machine, so I cannot provide a good example)

Thanks again guys!

**Comment by Akira1San** [comment]
Yes, its the same as the link i posted. Unless its from my gaming mouse.
