### ISSUE TITLE
Godot 3.1 Globals Error

### ISSUE THREAD

**Issue by JonathanGrant92** [TwistedTwigleg/Godot_FPS_Tutorial#27]
I downloaded the files and imported to a fresh project on Godot 3.1.1. I attempted to run the main menu scene, but an error is thrown. 
Error
Invalid get index 'mouse_sensitivity' (on base: 'null instance').

According to the debugger, local variable globals is never initialized to anything other than null.

I'm unsure how to fix this.

**Comment by TwistedTwigleg** [comment]
Strange. It should be set in globals, as [this line](https://github.com/TwistedTwigleg/Godot_FPS_Tutorial/blob/master/Globals.gd#L28) of code defines it and [this line](https://github.com/TwistedTwigleg/Godot_FPS_Tutorial/blob/master/Player.gd#L163) retrieves the value from globals.

Do you know which script is causing the error?

**Comment by TwistedTwigleg** [comment]
Closed due to the tutorial being archived.
(Thanks for the bug report though! While I was never able to reproduce the issue, I appreciate the report!)
