### ISSUE TITLE
RQ: 2 features: display fps and press a key to quit game

### ISSUE THREAD

**Issue by Akira1San** [TwistedTwigleg/Godot_FPS_Tutorial#4]
Add display fps to see the game frames in game.
Add Esc key to quit the game.

**Comment by TwistedTwigleg** [comment]
Thanks Akira1San!

> Add display fps to see the game frames in game

You can see the FPS currently on the debugger, under the `Monitors` tab from the editor.

While having a FPS display can help for exported games, it doesn't really help when you are running from the editor. Personally I think it is best to leave this out, as it does not really relate to making a FPS game (in my opinion).

This [Godot answer](https://godotengine.org/qa/9687/get-the-label-text-to-be-the-fps) post shows it's fairly simple, but I personally think it is best to leave it to the reader.

> Add Esc key to quit the game.

Currently `Esc` frees/captures the mouse cursor. We would have to change which key frees/captures the mouse cursor. I'm fine with having `Esc` quit the game (then it could be extended to a pause menu later ) but what key would you suggest changing the freeing/capturing of the mouse cursor to?

**Comment by Akira1San** [comment]
I see. Im just used to see the fps on screen using fraps, but for some reason fraps dont work here. I agree Esc key should be for the menu screen.

**Comment by TwistedTwigleg** [comment]
Maybe "show fps" option in a debug sub menu in the pause screen? Then it would be the best of both worlds.

(Since I am doing this in my spare time, I cannot guarantee I will add a pause screen. That said, I'll add it to the list of things to do!)

**Comment by Akira1San** [comment]
Sure. I would only suggest for some of the last parts of the fps tut, maybe an main menu. :)
I also added the 2 features and found some bugs, but dont know if they are known.

**Comment by TwistedTwigleg** [comment]
Sounds good! I will put making a debug menu on my list of things to do.
